repositories:
  - name: argo
    url: https://argoproj.github.io/argo-helm

releases:
  - name: argo-rollouts
    namespace: argo-rollouts
    forceNamespace: argo-rollouts
    chart: argo/argo-rollouts
    version: 2.34.1
    values:
      - argorollouts.yaml

  - name: rollout
    namespace: default
    forceNamespace: default
    chart: rollouts
    version: 0.1.0
